### ISSUE TITLE
키워드 알림 개선

### ISSUE THREAD

**Issue by yeonhoyoon** [hhertzog/haangnmarket#1]
안녕하세요! 제출해 주신 내용 잘 확인하였어요. 🙂 
키워드 알림을 받을 [사용자들을 뽑는 부분](https://github.com/hhertzog/haangnmarket/blob/304db6a6ede8e0867f5ad099e6de2ae792dfd3d7/app/controllers/posts_controller.rb#L31-L37)을 좀더 개선해 볼 방법이 있을까요?

이런 부분들에 대해 고민해 볼 수 있을 것 같아요.
* 이 코드를 이 위치에 두는것이 최선일지
* 매칭 대상을 좀더 효율적으로 찾을 수 있을지
* 게시글이 등록될 때마다 이 코드를 실행하면 게시글 등록에 걸리는 시간이 점점 오래걸리지 않을지

**Comment by hhertzog** [comment]
> 안녕하세요! 제출해 주신 내용 잘 확인하였어요. 🙂
> 키워드 알림을 받을 [사용자들을 뽑는 부분](https://github.com/hhertzog/haangnmarket/blob/304db6a6ede8e0867f5ad099e6de2ae792dfd3d7/app/controllers/posts_controller.rb#L31-L37)을 좀더 개선해 볼 방법이 있을까요?
> 
> 이런 부분들에 대해 고민해 볼 수 있을 것 같아요.
> 
> * 이 코드를 이 위치에 두는것이 최선일지
> * 매칭 대상을 좀더 효율적으로 찾을 수 있을지
> * 게시글이 등록될 때마다 이 코드를 실행하면 게시글 등록에 걸리는 시간이 점점 오래걸리지 않을지

안녕하세요^^ 코드리뷰 감사합니다!
지적하신 것들을 더 고민하고 공부해보았습니다.


•	이 코드를 이 위치에 두는것이 최선일지

저도 이 위치에 두는 것이 최선이 아니라고 생각합니다. 이전 저의 코드의 제일 큰 문제는 게시글 올린 후 글쓴 유저가 알림 보내지는 것을 기다려야 하는 점입니다. 알림을 보내는 코드 부분이synchronous(동기식)으로 실행되기 때문에 게시글을 올린 유저는 모든 알림이 보내지는 것을 기다려야 합니다. 그래서 유저의 수가 많아지고, 등록된 키워드가 늘어날수록 오래 걸리고 큰 문제가 됩니다. 이러한 상황을 방지하기 위해서 게시글이 올라간 후에 알림을 보내는 방법을 찾아봤더니, “Active Record callbacks”이라는 것을 발견했습니다. 
[이 기사](https://engineering.gusto.com/the-rails-callbacks-best-practices-used-at-gusto/)를 읽고  callbacks에 대해 더 배웠습니다. 기사에 따르면 callback을 사용할 때, after_save보다 after_commit이 더 안전하다고 합니다. 왜냐하면, after_commit이 callback 중에 유일하게 데이터베이스 트랜잭션이 완료된 다음에 실행되기 때문입니다. 알림이 보내진 직 후, 그리고 게시글이 데이터베이스에 commit되기 전 그 사이에 에러가 생길 수 있기 때문에, 존재하지 않는 게시글에 대한 알림을 사용자들이 받을 수 있습니다.  
게시글을 올린 유저가 기다려야 하는 시간을 줄이기 위해서, 그리고 에러가 생긴 게시글에 대한 알림 보내지 않기 위해서 after_commit을 사용하기로 했습니다!


•	매칭 대상을 좀더 효율적으로 찾을 수 있을지


키워드 받을 수 있는 유저들은 키워드가 등록된 유저들뿐입니다. 그래서 매칭 대상을 좀 더 효율적으로 찾기 위해 [table join & group by user.id](https://github.com/hhertzog/haangnmarket/blob/main/app/models/post.rb#L13)를 사용하여 키워드를 등록한 유저들 대상으로만 뽑아봤습니다.
또한, 지금 저의 코드는 전국의 모든 유저들에게 알림을 보내지만, 그것은 비효율적일 것 같습니다. 당근마켓처럼 이 동네 근처에 있는 유저들을 대상으로 뽑는 것이 더 효율적일 것 같습니다. 키워드 등록할 때 "알림 받고 싶은 동네" 선택란도 추가할 생각입니다! 


•	게시글이 등록될 때마다 이 코드를 실행하면 게시글 등록에 걸리는 시간이 점점 오래걸리지 않을지


이 코드는 동기식으로 실행되기 때문에 유저와 키워드가 많아질수록 게시글 등록에 걸리는 시간이 오래 걸립니다. 이 부분을 고치기 위해서 asynchronous(비동기식)으로 실행하는 것이 더 좋을 것 같습니다!
Rails코드를 비동기식으로 실행하는 방법을 공부하면서 “Sidekiq”이라는 것이 자주 언급되는 것을 보았습니다. Sidekiq은 “Redis” 데이터 관리 시스템을 사용하는데, 빠르고 대규모 환경에서도 잘 돼서 인기가 많은 것 같습니다. 저도 원래 Sidekiq을 쓰려고 했지만 Redis를 Heroku에 추가하려면 신용카드 번호 넣어야 했고, 그 방법은 제게 부담이 되어 다른 방식 찾아봤습니다. 
저는 결국 “Active Job” 프레임워크와 “Delayed Job”으로 비동기식 알림 시스템을 만들어봤습니다. Delayed Job은 queuing backend입니다. Sidekiq과 달리 데이터 관리 시스템이 따로 필요하지 않고, 기존의 데이터베이스를 사용합니다. 작은 규모로는 괜찮은데 규모가 커지면 Sidekiq이 더 나을 것 같습니다. 하지만 Active Job 프레임워크의 장점 중에 하나는 queuing backend를 쉽게 바꿀 수 있다는 점입니다. 나중에 규모가 커지면 Sidekiq으로 바꿀 수 있습니다.

Active Job & Delayed Job에 대한 정보:

1. [Active Job 매뉴얼](https://guides.rubyonrails.org/active_job_basics.html)
2. [Active Job 사용법, queuing backend 바꾸는 방법](https://www.cloudbees.com/blog/how-to-use-rails-active-job/)
3. [Delayed Job과 Sidekiq 비교](https://www.sqlbot.co/blog/delayed-job-vs-sidekiq-which-one-should-you-choose#:~:text=Delayed%20Job%20allows%20you%20to,your%20program%2C%20DJ%20outshines%20Sidekiq.&text=This%20makes%20using%20the%20framework,use%20in%20comparison%20to%20Sidekiq.)

제 코드를 리뷰해주셔서 다시 한번 감사합니다!

**Comment by yeonhoyoon** [comment]
레일즈 프레임워크에 익숙하지 않으셨을 텐데도 자세히 답변주시고, 또 코드도 개선해 주셔서 감사드려요!
답변해주신 내용을 읽고, 아래 부분들에 대해 추가적으로 궁금함이 생겼어요.
(github에는 답변을 꼭 달아주시지 않아도 됩니다. 면접때 상황에 따라, 이런 내용들을 여쭤보게 될 수도 있을 것 같아요.)

--

> 게시글을 올린 유저가 기다려야 하는 시간을 줄이기 위해서, 그리고 에러가 생긴 게시글에 대한 알림 보내지 않기 위해서 after_commit을 사용하기로 했습니다!
* "Active Record Callback"에 있는 코드는 synchronous하게 실행되나요? 아니면 asynchronous하게 실행되나요?
* 왜 after_save보다 after_commit이 안전한 것인지? "게시글이 데이터베이스에 commit되기 전 그 사이에 에러가 생길 수 있기 때문에" 이 이유가 맞는지?
